# Pi-hole Manager: lease file for embedded dnsmasq running as user pihole.
# Required when /etc/dnsmasq.d contains DHCP/PXE directives like dhcp-range, dhcp-boot or pxe-service.
dhcp-leasefile=/etc/pihole/dhcp.leases
