# opsi / PXE proxy boot example
# Adjust network, opsi/TFTP server IP, and boot paths.
dhcp-range=192.168.222.0,proxy
#dhcp-option=66,192.168.222.140
#dhcp-option=67,linux/pxelinux.0
dhcp-boot=linux/pxelinux.0,192.168.222.140,192.168.222.0
pxe-service=x86PC,"Automatic Network boot",linux/pxelinux.0,192.168.222.140
pxe-service=X86-64_EFI,"Boot from network EFI",linux/pxelinux.cfg/shimx64.efi.signed,192.168.222.140
pxe-service=BC_EFI,"Boot from network",linux/pxelinux.cfg/shimx64.efi.signed,192.168.222.140
